version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  client:
      build:
        context: ./client
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app
      networks:
        - app-network

volumes:
  mongo-data:

networks:
  app-network:
   
